# Set the build language to Python
language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  # - pip install -U drf-yasg

before_script:
  - cp .env.example .env
  - python manage.py migrate

# command to run tests
script:
  - pytest
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - codecov
