language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - cp .env
  - python manage.py migrate

# command to run tests
script:
  - pytest
