# Generated by Django 2.2.4 on 2019-10-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=False, help_text='Switch between approved comments', verbose_name='Approved comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(help_text='Comments goes here', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Create at', verbose_name='Create at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updating data', verbose_name='Updated at'),
        ),
    ]
