# Generated by Django 2.2.4 on 2019-09-15 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Post Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='comments.Comment')),
            ],
            options={
                'verbose_name': 'My Post',
                'verbose_name_plural': 'My Posts',
            },
        ),
    ]
